# 应用名称
spring:
  application:
    name: zuul-net


server:
  port: 6060

eureka:
  client:
    service-url:
      defaultZone: http://zhangyibing:123456@euk1.com:7900/eureka/,http://zhangyibing:123456@euk2.com:7901/eureka/,http://zhangyibing:123456@euk3.com:7902/eureka/

zuul:
  servlet-path: /
  routes:
    route1:       # 随意写的区分不同映射服务器的名称（只是区分不同的映射服务器）
      path: /zuul/**    # 自定义映射服务器路径的名称（相当于key，外部访问这个地址会映射到下面的service-id这个value值。然后从eureka服务列表找到对应服务名称，进而负载均衡的请求一个服务器）
      service-id: eureka-client-consumer     # eureka注册中心中要映射的服务名称，因为是双层map结构，所以可以实现负载均衡和高可用
    