eureka:
  client:
    #设置服务注册中心的URL，用于client和server端交流
    service-url:
      #带有zone的原因是最初该项目在亚马逊上部署，因此有部分配置沿用了早期的配置，配置多个地址的话就可以向多个节点去注册
      defaultZone: http://zhangyibing:123456@euk1.com:7900/eureka/,http://zhangyibing:123456@euk2.com:7901/eureka/,http://zhangyibing:123456@euk3.com:7902/eureka/
    #开启手动控制，将自己真正的健康状态传播到Server
    healthcheck:
      enabled: true
server:
  port: 9091
  servlet:
    context-path: /consumer

spring:
  application:
    name: eureka-client-consumer




management:
  #开启上报本节点的信息，*代表上报本节点所有的信息
  endpoints:
    web:
      exposure:
        include: '*'
  #开启之后，可以远程关闭该节点,但是只支持POST请求
  endpoint:
    shutdown:
      enabled: true


#Feign默认支持Ribbon；Ribbon的重试机制和Feign的重试机制有冲突，所以源码中默认关闭Feign的重试机制,使用Ribbon的重试机制
#ribbon超时时间只能配置在consumer端
#ribbon:
#  #连接超时时间
#  ConnectTimeout: 1000
#  #业务逻辑等待超时时间
#  ReadTimeout: 100
#  #同一台实例最大重试次数,不包括首次调用
#  MaxAutoRetries: 3
#  #重试负载均衡其他的实例最大重试次数,不包括首次调用
#  MaxAutoRetriesNextServer: 3
#  #是否所有操作都重试
#  OkToRetryOnAllOperations: false

feign:
  hystrix:
    enabled: true

hystrix:
  dashboard:
    proxy-stream-allow-list: localhost
#hystrix:
#  command:
#    default:
#      execution:
#        isolation:
#          strategy: SEMAPHORE

