

eureka:
  client:
    #设置服务注册中心的URL，用于client和server端交流
    service-url:
      #带有zone的原因是最初该项目在亚马逊上部署，因此有部分配置沿用了早期的配置，配置多个地址的话就可以向多个节点去注册
      defaultZone: http://zhangyibing:123456@euk1.com:7900/eureka/,http://zhangyibing:123456@euk2.com:7901/eureka/,http://zhangyibing:123456@euk3.com:7902/eureka/
    healthcheck:
      enabled: true
server:
  port: 8080
  servlet:
    context-path: /service

spring:
  application:
    name: eureka-client-service
  zipkin:
        baseUrl: http://localhost:9411
  boot:
    admin:
      client:
        url: http://localhost:8888



management:
  #开启上报本节点的信息，*代表上报本节点所有的信息
  endpoints:
      web:
        exposure:
          include: '*'
  #开启之后，可以远程关闭该节点,但是只支持POST请求
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true

